server:
  port: 8080
  servlet:
    context-path: /api
  # HTTP请求大小限制
  max-http-header-size: 1MB

spring:
  application:
    name: coach-ai-core-service
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  
  # HTTP请求配置
  mvc:
    max-request-size: 50MB
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:47.112.214.8}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:coach_ai}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:test123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

# MinIO 文件存储配置
minio:
  endpoint: ${MINIO_ENDPOINT:http://120.77.56.132:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin123}
  bucket-name: ${MINIO_BUCKET_NAME:coach-ai-files}
  secure: ${MINIO_SECURE:false}
  # 文件上传配置
  upload:
    max-file-size: 20MB
    max-request-size: 20MB
  # 存储路径配置
  paths:
    images: images/
    documents: documents/
    temp: temp/

# AI工作流配置
ai:
  workflow:
    # 基础配置
    base-url: https://apaas.alibaba-inc.com/common/invoke
    timeout: 120000  # 2分钟超时，单位毫秒
    
    # 姿态分析工作流配置
    pose-analysis:
      api-code: 360000000003870008
      ak: 445752-b3f1-mbs3Z1OiBL2u4fo5NDwe

# 日志配置
logging:
  level:
    com.coachai: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

