server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: coach-ai-core-service
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:47.112.214.8}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:coach_ai}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:test123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

# 日志配置
logging:
  level:
    com.coachai: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

