server:
  port: 8080
  servlet:
    context-path: /api
  # HTTP请求大小限制
  max-http-header-size: 1MB
  
  # Tomcat优化配置
  tomcat:
    connection-timeout: 360000     # 6分钟，大于AI工作流最大处理时间
    keep-alive-timeout: 60000      # 1分钟，保持连接活跃
    max-connections: 200           # 最大连接数
    threads:
      max: 200                     # 最大工作线程
      min-spare: 10               # 最小空闲线程

spring:
  application:
    name: coach-ai-core-service
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  
  # HTTP请求配置
  mvc:
    max-request-size: 50MB
    # 异步请求配置
    async:
      request-timeout: 360000      # 6分钟，与Tomcat保持一致
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:47.112.214.8}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:coach_ai}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:test123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

# 阿里云OSS 文件存储配置
oss:
  endpoint: ${OSS_ENDPOINT:https://oss-cn-shenzhen.aliyuncs.com}
  access-key-id: ${OSS_ACCESS_KEY_ID}
  access-key-secret: ${OSS_ACCESS_KEY_SECRET}
  bucket-name: ${OSS_BUCKET_NAME:cri-537ixr7zm3jj17zu-registry}
  region: ${OSS_REGION:cn-shenzhen}
  secure: ${OSS_SECURE:true}
  # CDN域名（可选）
  cdn-domain: ${OSS_CDN_DOMAIN:}
  # 自定义域名（可选）
  custom-domain: ${OSS_CUSTOM_DOMAIN:}
  # 连接配置
  connection-timeout: ${OSS_CONNECTION_TIMEOUT:50000}
  socket-timeout: ${OSS_SOCKET_TIMEOUT:50000}
  # 文件上传配置
  upload:
    max-file-size: 20MB
    max-request-size: 20MB
  # 存储路径配置
  paths:
    images: images/
    documents: documents/
    temp: temp/

# 图片压缩配置
image:
  compression:
    # 是否启用图片压缩
    enabled: true
    # 默认压缩质量 (0.1-1.0)
    default-quality: 0.8
    # 最大宽度
    max-width: 1920
    # 最大高度
    max-height: 1920
    # 压缩阈值，超过此大小的图片将被压缩 (单位: 字节)
    compression-threshold: 524288  # 512KB
    # 智能压缩策略
    smart-compression:
      # 大文件 (>5MB) 压缩参数
      large-file:
        size-threshold: 5242880    # 5MB
        quality: 0.6
        max-width: 1920
        max-height: 1920
      # 中等文件 (>2MB) 压缩参数  
      medium-file:
        size-threshold: 2097152    # 2MB
        quality: 0.7
        max-width: 1920
        max-height: 1920
      # 小文件 (>500KB) 压缩参数
      small-file:
        size-threshold: 524288     # 512KB
        quality: 0.8
        max-width: 1920
        max-height: 1920

# AI工作流配置
ai:
  workflow:
    # 基础配置
    base-url: https://apaas.alibaba-inc.com/common/invoke
    connection-timeout: 60000      # 连接超时60秒 - 适应公网到内网的连接延迟
    read-timeout: 300000          # 读取超时5分钟 - 允许AI处理
    timeout: 120000               # 兼容性保留，已废弃
    
    # 姿态分析工作流配置
    pose-analysis:
      api-code: 360000000003870008
      ak: 445752-b3f1-mbs3Z1OiBL2u4fo5NDwe

    # 症状分析工作流配置
    issue-analysis:
      api-code: 360000000003862008
      ak: 445752-b3f1-mbs3Z1OiBL2u4fo5NDwe

# 日志配置
logging:
  level:
    com.coachai: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

