server:
  port: 8080
  servlet:
    context-path: /api
  # HTTP请求大小限制
  max-http-header-size: 1MB

spring:
  application:
    name: coach-ai-core-service
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  
  # HTTP请求配置
  mvc:
    max-request-size: 50MB
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:47.112.214.8}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:coach_ai}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:test123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

# 阿里云OSS 文件存储配置
oss:
  endpoint: ${OSS_ENDPOINT:https://oss-cn-shenzhen.aliyuncs.com}
  access-key-id: ${OSS_ACCESS_KEY_ID}
  access-key-secret: ${OSS_ACCESS_KEY_SECRET}
  bucket-name: ${OSS_BUCKET_NAME:cri-537ixr7zm3jj17zu-registry}
  region: ${OSS_REGION:cn-shenzhen}
  secure: ${OSS_SECURE:true}
  # CDN域名（可选）
  cdn-domain: ${OSS_CDN_DOMAIN:}
  # 自定义域名（可选）
  custom-domain: ${OSS_CUSTOM_DOMAIN:}
  # 连接配置
  connection-timeout: ${OSS_CONNECTION_TIMEOUT:50000}
  socket-timeout: ${OSS_SOCKET_TIMEOUT:50000}
  # 文件上传配置
  upload:
    max-file-size: 20MB
    max-request-size: 20MB
  # 存储路径配置
  paths:
    images: images/
    documents: documents/
    temp: temp/

# AI工作流配置
ai:
  workflow:
    # 基础配置
    base-url: https://apaas.alibaba-inc.com/common/invoke
    timeout: 120000  # 2分钟超时，单位毫秒
    
    # 姿态分析工作流配置
    pose-analysis:
      api-code: 360000000003870008
      ak: 445752-b3f1-mbs3Z1OiBL2u4fo5NDwe

    # 症状分析工作流配置
    issue-analysis:
      api-code: 360000000003862008
      ak: 445752-b3f1-mbs3Z1OiBL2u4fo5NDwe

# 日志配置
logging:
  level:
    com.coachai: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

